### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by LylyG** [LylyG/time_tracking_app#1]
### Phase One

- [ ] Anyone can list/create/edit/delete developers.
- [ ] Developers must have unique email addresses.
- [ ] Anyone can create a time entry for any developer.
- [ ] The time entry form should include a dropdown for selecting the developer by name, not by id.
- [ ] Time entries must have a duration, a developer, and a date.
- [ ] The developer index page should have a link to the time entry creation page, and vice-versa.
- [ ] Submitting a new time entry should redirect somewhere sensible.
- [ ] The application should have a root route.

### Phase Two

- [ ] Developers can log in.
- [ ] Developers can log out from any page.
- [ ] Anyone who tries to access any page without logging in is redirected to the login page.
- [ ] The application should have a root route which is NOT the login page.

### Phase Three

- [ ] Developers can only create time entries for themselves.
- [ ] Developers can see a list of just their own time entries.
- [ ] Developers can edit/delete just their own time entries.

### Phase Four

- [ ] Developers can list/create/edit/delete projects.
- [ ] Projects must have a maximum number of allowed hours.
- [ ] When time entries are created or updated, they must have a project associated with each one.
- [ ] The time entry form should include a dropdown for selecting the project by name, not by id.
- [ ] There must be a project list page which:
- [ ] Includes a total number of hours worked on each project.
- [ ] Shows the project in red if the total number of hours on the project exceeds the number of hours allowed.

### Phase Five

- [ ] No one can delete a developer once that developer has made a time entry.
- [ ] No one can delete a project once that project has a time entry on it.
- [ ] Modify the developer list page to:
- [ ] Show the developer in red if he or she has worked more than 40 hours in the current calendar week
